#!/usr/bin/env python3
"""
Upload NCB API test data JSON files to Google Shared Drive.

This script uploads the generated NCB test JSON files to Google Shared Drive
for sharing with the NCB team and for integration testing.

UPDATED: Now supports Google Shared Drives with supportsAllDrives=True parameter.
See docs/GOOGLE_SHARED_DRIVE_SETUP.md for setup instructions.
"""

import json
import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from src.config.settings import settings
from src.utils.logging import configure_logging, get_logger

configure_logging()
logger = get_logger(__name__)


def upload_to_drive(file_path: Path, folder_id: str) -> str:
    """
    Upload a file to Google Shared Drive.

    Args:
        file_path: Path to the file to upload
        folder_id: Google Shared Drive folder ID

    Returns:
        File ID of uploaded file
    """
    try:
        # Load credentials
        creds = Credentials.from_service_account_file(
            settings.drive.credentials_path,
            scopes=['https://www.googleapis.com/auth/drive.file']
        )

        # Build Drive API client
        service = build('drive', 'v3', credentials=creds)

        # File metadata
        file_metadata = {
            'name': file_path.name,
            'parents': [folder_id],
            'description': 'NCB API test data generated by Claims Data Entry Agent'
        }

        # Upload file
        media = MediaFileUpload(
            str(file_path),
            mimetype='application/json',
            resumable=True
        )

        # ✅ UPDATED: Add supportsAllDrives=True for Shared Drive support
        file = service.files().create(
            body=file_metadata,
            media_body=media,
            fields='id, name, webViewLink',
            supportsAllDrives=True  # 🔑 CRITICAL: Required for Google Shared Drives
        ).execute()

        logger.info(
            "File uploaded to Google Shared Drive",
            file_id=file.get('id'),
            file_name=file.get('name'),
            web_link=file.get('webViewLink')
        )

        return file.get('id')

    except Exception as e:
        logger.error(f"Failed to upload file to Shared Drive: {e}", file=str(file_path))
        raise


def main():
    """Upload all NCB test JSON files to Google Shared Drive."""

    logger.info("Starting NCB test data upload to Google Shared Drive")

    # Define test data files
    fixtures_dir = Path(__file__).parent.parent / "tests" / "fixtures"
    test_files = [
        fixtures_dir / "ncb_test_data.json",
        fixtures_dir / "ncb_single_valid_claim.json",
        fixtures_dir / "ncb_batch_claims.json"
    ]

    # Check files exist
    for file_path in test_files:
        if not file_path.exists():
            logger.error(f"Test file not found: {file_path}")
            sys.exit(1)

    # Get Drive folder ID from settings
    folder_id = settings.drive.folder_id
    if not folder_id:
        logger.error("Google Shared Drive folder ID not configured in settings")
        logger.info("Please set DRIVE_FOLDER_ID in .env file")
        logger.info("See docs/GOOGLE_SHARED_DRIVE_SETUP.md for setup instructions")
        sys.exit(1)

    logger.info(f"Uploading {len(test_files)} files to Shared Drive folder: {folder_id}")

    # Upload each file
    uploaded_files = []
    for file_path in test_files:
        try:
            file_id = upload_to_drive(file_path, folder_id)
            uploaded_files.append({
                'name': file_path.name,
                'file_id': file_id,
                'path': str(file_path)
            })
            logger.info(f"✅ Uploaded: {file_path.name}")
        except Exception as e:
            logger.error(f"❌ Failed to upload {file_path.name}: {e}")

    # Summary
    logger.info("="*60)
    logger.info(f"Upload complete: {len(uploaded_files)}/{len(test_files)} files")
    logger.info("="*60)

    # Print results
    print("\n📁 Uploaded NCB Test Files to Shared Drive:")
    print("="*60)
    for file_info in uploaded_files:
        print(f"  ✅ {file_info['name']}")
        print(f"     File ID: {file_info['file_id']}")

    # Create summary JSON
    summary_path = fixtures_dir / "ncb_drive_upload_summary.json"
    with open(summary_path, 'w') as f:
        json.dump({
            'upload_timestamp': '2024-12-24T18:45:00Z',
            'folder_id': folder_id,
            'uploaded_files': uploaded_files,
            'total_files': len(uploaded_files),
            'shared_drive': True  # Flag indicating Shared Drive usage
        }, f, indent=2)

    logger.info(f"Summary saved to: {summary_path}")
    print(f"\n📝 Upload summary: {summary_path}")
    print("\n💡 Tip: View files at https://drive.google.com/drive/shared-drives")

    return 0


if __name__ == '__main__':
    sys.exit(main())
